library(UpSetR)
#int_all_qlf <- diffexpr(all_int = TRUE, all_bin = TRUE, int = TRUE, ebin = FALSE, CCR = FALSE)
#ebin_all_qlf <- diffexpr(all_int = TRUE, all_bin = TRUE, int = FALSE, ebin = TRUE, CCR = FALSE)
#CCR_all_qlf <-  diffexpr(all_int = TRUE, all_bin = TRUE, int = FALSE, ebin = FALSE, CCR = TRUE)
ebin_pos_qlf <- diffexpr(all_int = FALSE, all_bin = TRUE, int = FALSE, ebin = TRUE, CCR = FALSE)
int_1_qlf <- diffexpr(all_int = TRUE, all_bin = FALSE, int = TRUE, ebin = FALSE, CCR = FALSE)
int1tags <- data.frame(topTags(int_1_qlf, n = nrow(int_1_qlf))) %>% filter(FDR < 0.05)
ebin_pos_tags <- data.frame(topTags(ebin_pos_qlf_after, n = nrow(ebin_pos_qlf))) %>% filter(FDR < 0.05)
intTags <- data.frame(topTags(int_all_qlf, n = nrow(int_all1_qlf))) %>% filter(FDR < 0.05)
ebinTags <- data.frame(topTags(ebin_all_qlf, n = nrow(ebin_all_qlf))) %>% filter(FDR < 0.05)
CCRtags <- data.frame(topTags(CCR_all_qlf, n = nrow(CCR_all_qlf))) %>% filter(FDR < 0.05)
for_upset <- list(int_pos_vs_neg = row.names(intTags), IMU_vs_KRT =  row.names(CCRtags), "ebin1_vs_0" = 
                                    row.names(ebin_pos_tags))
upset(fromList(for_upset), order.by = "freq")